######################################################################################
###  ██╗░░░░░██╗░██████╗░██╗░░██╗████████╗░██╗░░░░░░░██╗░█████╗░██╗░░░░░███████╗   ###
###  ██║░░░░░██║██╔════╝░██║░░██║╚══██╔══╝░██║░░██╗░░██║██╔══██╗██║░░░░░██╔════╝   ###
###  ██║░░░░░██║██║░░██╗░███████║░░░██║░░░░╚██╗████╗██╔╝██║░░██║██║░░░░░█████╗░░   ###
###  ██║░░░░░██║██║░░╚██╗██╔══██║░░░██║░░░░░████╔═████║░██║░░██║██║░░░░░██╔══╝░░   ###
###  ███████╗██║╚██████╔╝██║░░██║░░░██║░░░░░╚██╔╝░╚██╔╝░╚█████╔╝███████╗██║░░░░░   ###
###  ╚══════╝╚═╝░╚═════╝░╚═╝░░╚═╝░░░╚═╝░░░░░░╚═╝░░░╚═╝░░░╚════╝░╚══════╝╚═╝░░░░░   ###
######################################################################################
# Связь с разработчиком:
# VK - @lightwolf7
# TG - @lightwolf

messages:
  not_enough_money: "&cУ вас недостаточно средств для оплаты объявления."
  no_permission: "&cУ вас нет прав на отправку объявлений."
# Стоимость каждой операции
cost:
  ad: 5000
  buy: 5000
  bc: 5000

# Права доступа к командам
permissions:
  ad: "lwbroadcast.ad"
  buy: "lwbroadcast.buy"
  bc: "lwbroadcast.bc"

# Префиксы для каждой команды
prefix:
  ad: "&e[Продажа] &7"
  buy: "&e[Покупка] &7"
  bc: "&e[Объявление] &7"

# Сообщения об использовании для каждой команды
usage:
  ad: "&cИспользование: /ad <текст>"
  buy: "&cИспользование: /buy <текст>"
  bc: "&cИспользование: /bc <текст>"